### ISSUE TITLE
Feedback on submission

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/r-python-exercises1-syedaslamsheikdawood#1]
Hi Aslam, 

The submission looks good. If possible, can you submit the Jupyter Notebook the HTML is derived from? This will be expected for the next assignment. 

You will receive full credit for this submission. Great work!
-Greg

**Comment by Syedaslamsheikdawood** [comment]
Hi Sir, I have uploaded the HW1.ipynb for this assignment.
-Syed
